### ISSUE TITLE
Switch to rbvmomi2

### ISSUE THREAD

**Issue by micwoj92** [voxpupuli/beaker-vmware#40]
https://github.com/voxpupuli/beaker-vmware/blob/534fd0cdd0e2aa877240dcd148cbb02df0c6a3f7/beaker-vmware.gemspec#L29
[rbvmomi2](https://github.com/ManageIQ/rbvmomi2) is a maintained fork of [rbvmomi](https://github.com/vmware-archive/rbvmomi)

**Comment by bastelfreak** [comment]
done :)

**Comment by micwoj92** [comment]
Thank you, should I also open additional requests for gems in this org that depend on rbvmomi?

**Comment by bastelfreak** [comment]
@micwoj92 yes please :)
